
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"Yusheng-UCSBOrganization-IndexPage","number":121,"title":"Yusheng ucsb organization index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/121"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-UCSBOrganization-NewIndexPage","number":120,"title":"Yusheng ucsb organization new index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/120"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-UCSBOrganization-NewEditPage","number":116,"title":"Yusheng ucsb organization new edit page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/116"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-UCSBOrganization-CreatePage","number":107,"title":"Yusheng ucsb organization create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/107"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-UCSBOrganization-Placeholders","number":87,"title":"Yusheng ucsb organization placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/87"}]
