
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-Articles-editpage2","number":122,"title":"Fixing errors for main","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/122"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-UCSBOrganization-NewIndexPage","number":120,"title":"Yusheng ucsb organization new index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-2/pull/120"}]
